"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['FunTik.py']
DATA_FILES = [
        'Resources/favicon.png',
        ]
OPTIONS = {
        'argv_emulation': True,
        'iconfile': 'app.icns',
        'packages': [
            'AppKit',
            ],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
